### ISSUE TITLE
Code error in an user/mq7.c file

### ISSUE THREAD

**Issue by yangfanaixuexi** [3703781/MWLib#1]
I encountered the following error while running the author's code:
user\mq7.c(70): error:  #20: identifier "ADC_fghhvnbvglyPrescaler_Div4" is undefined
      ADC_CommonInitStructure.ADC_Prescaler = ADC_fghhvnbvglyPrescaler_Div4;
user\mq7.c: 0 warnings, 1 error
So I changed ADC_fghhvnbvglyPrescaler_Div4 to ADC_Prescaler_Div4 and then ran the code without any errors. I hope the author can confirm whether this error really exists when they see it.
Of course， My English is very bad, So I hope the author can 理解 what I say.

**Comment by 3703781** [comment]
Definitely it is a typo. Probably because I dozed off to the keyboard while coding. And my English is very bad too, so that I feels myself know exactly what you mean. Thank you for give me feedback on this issue.
